---
apiVersion: philipdouglass.com/v1
kind: PostgreSQLUser
metadata:
  name: samplepguser
  labels:
    app.kubernetes.io/name: sampleapp
spec:
  db: sampledb
  username: sampleuser
  # Or using a configmap:
  # username:
  #   valueFrom:
  #     configMapKeyRef:
  #       name: sample-username
  #       key: sampleuser
  # password: my-secret-password
  # Prefer using a secret:
  password:
    valueFrom:
      secretKeyRef:
        name: sample-secret
        key: sample-password
